services:
  mysql:
    image: mysql:5.7.33
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
  smtp:
    image: schickling/mailcatcher # MailCatcher https://mailcatcher.me/
    ports:
      - "1080:1080"
      - "1025:1025"
  rails:
    build: .
    command: ./entrypoint.sh
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - smtp