# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mysql
  username: root
  password: password

development:
  <<: *default
  database: rails_jwt_demo_development

test:
  <<: *default
  database: rails_jwt_demo_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: rails_jwt_demo_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
